[font]
size = 8.5

[font.normal]
family = "FiraCode Nerd Font"

[selection]
save_to_clipboard = true

# papercolor
[colors.primary]
background = '0x1c1c1c'
foreground = '0xd0d0d0'

[colors.cursor]
text       = '0x1c1c1c'
cursor     = '0xd0d0d0'

[colors.normal]
black      = '0x1c1c1c'
# original - too dark
# red        = '0xaf005f'
red        = '0xa24176'
# original - too dark
# green      = '0x5faf00'
green      = '0x7fba39'
yellow     = '0xd7af5f'
# original - too dark
# blue       = '0x5fafd7'
blue       = '0x69bbe4'
magenta    = '0x808080'
cyan       = '0xd7875f'
white      = '0xd0d0d0'

[colors.bright]
black      = '0x585858'
red        = '0x5faf5f'
green      = '0xafd700'
yellow     = '0xaf87d7'
blue       = '0xffaf00'
magenta    = '0xff5faf'
cyan       = '0x00afaf'
white      = '0x5f8787'
