[font]
size = 9.0

[font.normal]
family = "FiraCode Nerd Font"

[selection]
save_to_clipboard = true

# papercolor
[colors.primary]
background = '#1c1c1c'
foreground = '#d0d0d0'

[colors.cursor]
text       = '#1c1c1c'
cursor     = '#d0d0d0'

[colors.normal]
black      = '#1c1c1c'
# original - too dark
# red        = '#af005f'
red        = '#a24176'
# original - too dark
# green      = '#5faf00'
green      = '#7fba39'
yellow     = '#d7af5f'
# original - too dark
# blue       = '#5fafd7'
blue       = '#69bbe4'
magenta    = '#808080'
cyan       = '#d7875f'
white      = '#d0d0d0'

[colors.bright]
black      = '#585858'
red        = '#5faf5f'
green      = '#afd700'
yellow     = '#af87d7'
blue       = '#ffaf00'
magenta    = '#ff5faf'
cyan       = '#00afaf'
white      = '#5f8787'
